// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHa7ojry240eXpdeOwmZ7kGl9jcg4Icuc',
    appId: '1:49480162297:web:61061f8a574ba8dbcd7b28',
    messagingSenderId: '49480162297',
    projectId: 'mobilsatis-d9502',
    authDomain: 'mobilsatis-d9502.firebaseapp.com',
    storageBucket: 'mobilsatis-d9502.firebasestorage.app',
    measurementId: 'G-92N017QT56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCadASV7odJcuDObW_yrLMxhYOntmL0xr8',
    appId: '1:49480162297:android:7fbe6f778e796e0acd7b28',
    messagingSenderId: '49480162297',
    projectId: 'mobilsatis-d9502',
    storageBucket: 'mobilsatis-d9502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3pXLjcUD05xgt-LQsZiowap46k4HG-g',
    appId: '1:49480162297:ios:50ac194777bd4ef7cd7b28',
    messagingSenderId: '49480162297',
    projectId: 'mobilsatis-d9502',
    storageBucket: 'mobilsatis-d9502.firebasestorage.app',
    iosBundleId: 'com.example.mobilSatis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv3pXLjcUD05xgt-LQsZiowap46k4HG-g',
    appId: '1:49480162297:ios:50ac194777bd4ef7cd7b28',
    messagingSenderId: '49480162297',
    projectId: 'mobilsatis-d9502',
    storageBucket: 'mobilsatis-d9502.firebasestorage.app',
    iosBundleId: 'com.example.mobilSatis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHa7ojry240eXpdeOwmZ7kGl9jcg4Icuc',
    appId: '1:49480162297:web:d90b14c99c595791cd7b28',
    messagingSenderId: '49480162297',
    projectId: 'mobilsatis-d9502',
    authDomain: 'mobilsatis-d9502.firebaseapp.com',
    storageBucket: 'mobilsatis-d9502.firebasestorage.app',
    measurementId: 'G-Q1TB60DWY2',
  );
}
